# Generated by Django 3.2.7 on 2021-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=70)),
                ('company', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
